CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL,
    metadata_json TEXT NOT NULL
);

CREATE INDEX idx_events_event_timestamp ON events (event_timestamp);
CREATE INDEX idx_events_source_event_timestamp ON events (source, event_timestamp);
CREATE INDEX idx_events_source_event_id ON events (source, event_id);

CREATE TABLE correlation_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    source VARCHAR(255) NOT NULL,
    matched_event_id VARCHAR(255) NOT NULL,
    matched_source VARCHAR(255) NOT NULL,
    distance_km DOUBLE PRECISION NOT NULL,
    time_gap_seconds BIGINT NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_correlation_matches_detected_at ON correlation_matches (detected_at);
CREATE INDEX idx_correlation_matches_source_detected_at ON correlation_matches (source, detected_at);